package org.cxf.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-10-31T17:38:14.762+08:00
 * Generated source version: 3.2.0
 * 
 */
@WebService(targetNamespace = "http://ws.cxf.org/", name = "Isayhi")
@XmlSeeAlso({ObjectFactory.class})
public interface Isayhi {

    @WebMethod
    @RequestWrapper(localName = "sayhi", targetNamespace = "http://ws.cxf.org/", className = "org.cxf.ws.client.Sayhi")
    @ResponseWrapper(localName = "sayhiResponse", targetNamespace = "http://ws.cxf.org/", className = "org.cxf.ws.client.SayhiResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sayhi(
        @WebParam(name = "username", targetNamespace = "")
        java.lang.String username
    );
}
