package org.cxf.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-10-31T17:38:14.770+08:00
 * Generated source version: 3.2.0
 * 
 */
@WebServiceClient(name = "SayhiService", 
                  wsdlLocation = "http://localhost:8080/sayhi?wsdl",
                  targetNamespace = "http://ws.cxf.org/") 
public class SayhiService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.cxf.org/", "SayhiService");
    public final static QName SayhiPort = new QName("http://ws.cxf.org/", "SayhiPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/sayhi?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SayhiService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/sayhi?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SayhiService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SayhiService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SayhiService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public SayhiService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SayhiService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SayhiService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns Isayhi
     */
    @WebEndpoint(name = "SayhiPort")
    public Isayhi getSayhiPort() {
        return super.getPort(SayhiPort, Isayhi.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Isayhi
     */
    @WebEndpoint(name = "SayhiPort")
    public Isayhi getSayhiPort(WebServiceFeature... features) {
        return super.getPort(SayhiPort, Isayhi.class, features);
    }

}
