
package org.cxf.ws.notify.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-11-07T15:09:14.199+08:00
 * Generated source version: 3.2.0
 * 
 */
public final class ErpNoticeDHDResult_ErpNoticeDHDResultPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.ws.gw.sales.ec.org/", "ErpNoticeDHDResultService");

    private ErpNoticeDHDResult_ErpNoticeDHDResultPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ErpNoticeDHDResultService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ErpNoticeDHDResultService ss = new ErpNoticeDHDResultService(wsdlURL, SERVICE_NAME);
        ErpNoticeDHDResult port = ss.getErpNoticeDHDResultPort();  
        
        {
        System.out.println("Invoking noticeDHD...");
        java.lang.Integer _noticeDHD_yt = null;
        java.lang.String _noticeDHD_dhdbh = "";
        java.lang.Integer _noticeDHD_ddlx = null;
        java.lang.Integer _noticeDHD_status = null;
        org.cxf.ws.notify.client.InterfaceResult _noticeDHD__return = port.noticeDHD(_noticeDHD_yt, _noticeDHD_dhdbh, _noticeDHD_ddlx, _noticeDHD_status);
        System.out.println("noticeDHD.result=" + _noticeDHD__return);


        }

        System.exit(0);
    }

}
