package org.cxf.ws.notify.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-11-07T15:09:14.294+08:00
 * Generated source version: 3.2.0
 * 
 */
@WebService(targetNamespace = "http://service.ws.gw.sales.ec.org/", name = "ErpNoticeDHDResult")
@XmlSeeAlso({ObjectFactory.class})
public interface ErpNoticeDHDResult {

    @WebMethod
    @RequestWrapper(localName = "noticeDHD", targetNamespace = "http://service.ws.gw.sales.ec.org/", className = "org.cxf.ws.notify.client.NoticeDHD")
    @ResponseWrapper(localName = "noticeDHDResponse", targetNamespace = "http://service.ws.gw.sales.ec.org/", className = "org.cxf.ws.notify.client.NoticeDHDResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.cxf.ws.notify.client.InterfaceResult noticeDHD(
        @WebParam(name = "yt", targetNamespace = "")
        java.lang.Integer yt,
        @WebParam(name = "dhdbh", targetNamespace = "")
        java.lang.String dhdbh,
        @WebParam(name = "DDLX", targetNamespace = "")
        java.lang.Integer ddlx,
        @WebParam(name = "status", targetNamespace = "")
        java.lang.Integer status
    );
}
